# Import des Bibliothèques

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\richard kossi allado\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\users\richard kossi allado\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\richard kossi allado\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\richard kossi allado\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\richard kossi allado\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

data = pd.read_csv("PhiUSIIL_Phishing_URL_Dataset.csv")

data.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

# Colonnes de notre datasets

In [5]:
data.columns.tolist()

['FILENAME',
 'URL',
 'URLLength',
 'Domain',
 'DomainLength',
 'IsDomainIP',
 'TLD',
 'URLSimilarityIndex',
 'CharContinuationRate',
 'TLDLegitimateProb',
 'URLCharProb',
 'TLDLength',
 'NoOfSubDomain',
 'HasObfuscation',
 'NoOfObfuscatedChar',
 'ObfuscationRatio',
 'NoOfLettersInURL',
 'LetterRatioInURL',
 'NoOfDegitsInURL',
 'DegitRatioInURL',
 'NoOfEqualsInURL',
 'NoOfQMarkInURL',
 'NoOfAmpersandInURL',
 'NoOfOtherSpecialCharsInURL',
 'SpacialCharRatioInURL',
 'IsHTTPS',
 'LineOfCode',
 'LargestLineLength',
 'HasTitle',
 'Title',
 'DomainTitleMatchScore',
 'URLTitleMatchScore',
 'HasFavicon',
 'Robots',
 'IsResponsive',
 'NoOfURLRedirect',
 'NoOfSelfRedirect',
 'HasDescription',
 'NoOfPopup',
 'NoOfiFrame',
 'HasExternalFormSubmit',
 'HasSocialNet',
 'HasSubmitButton',
 'HasHiddenFields',
 'HasPasswordField',
 'Bank',
 'Pay',
 'Crypto',
 'HasCopyrightInfo',
 'NoOfImage',
 'NoOfCSS',
 'NoOfJS',
 'NoOfSelfRef',
 'NoOfEmptyRef',
 'NoOfExternalRef',
 'label']

# Recuperation de la colonne URL ET LABEL

In [6]:
data = data[["URL", "label"]].copy()

data.head()

                                  URL  label
0    https://www.southbankmosaics.com      1
1            https://www.uni-mainz.de      1
2      https://www.voicefmradio.co.uk      1
3         https://www.sfnmjournal.com      1
4  https://www.rewildingargentina.org      1

# Vérification du label

In [7]:
data['label'].value_counts()

label
1    134850
0    100945
Name: count, dtype: int64

# Features Engineering

In [8]:
from feature_engineering import extract_features

In [9]:
test_url = data["URL"].iloc[0]

print(test_url)
extract_features(test_url)

https://www.southbankmosaics.com

{'url_length': 32,
 'domain_length': 24,
 'path_length': 0,
 'query_length': 0,
 'number_of_subdomains': 1,
 'has_ip_address': 0,
 'uses_https': 1,
 'number_of_letters': 27,
 'number_of_digits': 0,
 'number_of_special_characters': 5,
 'letter_ratio': 0.84375,
 'digit_ratio': 0.0,
 'number_of_dots': 2,
 'number_of_hyphens': 0,
 'number_of_underscores': 0,
 'number_of_slashes': 2,
 'number_of_question_marks': 0,
 'number_of_equal_signs': 0,
 'number_of_ampersands': 0,
 'number_of_at_symbols': 0,
 'suspicious_keyword_count': 1}

In [10]:
sample = data.head(10).copy()

sample_features = pd.DataFrame(
    sample["URL"].apply(extract_features).tolist()
)

sample_features["label"] = sample["label"].values

sample_features

,url_length,domain_length,path_length,query_length,number_of_subdomains,has_ip_address,uses_https,number_of_letters,number_of_digits,number_of_special_characters,...,number_of_dots,number_of_hyphens,number_of_underscores,number_of_slashes,number_of_question_marks,number_of_equal_signs,number_of_ampersands,number_of_at_symbols,suspicious_keyword_count,label
0,32,24,0,0,1,0,1,27,0,5,...,2,0,0,2,0,0,0,0,1,1
1,24,16,0,0,1,0,1,18,0,6,...,2,1,0,2,0,0,0,0,0,1
2,30,22,0,0,2,0,1,24,0,6,...,3,0,0,2,0,0,0,0,0,1
3,27,19,0,0,1,0,1,22,0,5,...,2,0,0,2,0,0,0,0,0,1
4,34,26,0,0,1,0,1,29,0,5,...,2,0,0,2,0,0,0,0,0,1
5,31,23,0,0,1,0,1,26,0,5,...,2,0,0,2,0,0,0,0,0,1
6,26,18,0,0,1,0,1,21,0,5,...,2,0,0,2,0,0,0,0,0,1
7,26,18,0,0,1,0,1,21,0,5,...,2,0,0,2,0,0,0,0,0,1
8,30,22,0,0,1,0,1,25,0,5,...,2,0,0,2,0,0,0,0,0,1
9,19,11,0,0,1,0,1,14,0,5,...,2,0,0,2,0,0,0,0,0,1

## Application du features engineering au datasets

In [11]:
features_df = pd.DataFrame(
    data["URL"].apply(extract_features).tolist()
)

features_df["label"] = data["label"].values

In [12]:
features_df.head()

,url_length,domain_length,path_length,query_length,number_of_subdomains,has_ip_address,uses_https,number_of_letters,number_of_digits,number_of_special_characters,...,number_of_dots,number_of_hyphens,number_of_underscores,number_of_slashes,number_of_question_marks,number_of_equal_signs,number_of_ampersands,number_of_at_symbols,suspicious_keyword_count,label
0,32,24,0,0,1,0,1,27,0,5,...,2,0,0,2,0,0,0,0,1,1
1,24,16,0,0,1,0,1,18,0,6,...,2,1,0,2,0,0,0,0,0,1
2,30,22,0,0,2,0,1,24,0,6,...,3,0,0,2,0,0,0,0,0,1
3,27,19,0,0,1,0,1,22,0,5,...,2,0,0,2,0,0,0,0,0,1
4,34,26,0,0,1,0,1,29,0,5,...,2,0,0,2,0,0,0,0,0,1

In [13]:
features_df.shape

(235795, 22)

In [16]:
features_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 22 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   url_length                    235795 non-null  int64
 1   domain_length                 235795 non-null  int64
 2   path_length                   235795 non-null  int64
 3   query_length                  235795 non-null  int64
 4   number_of_subdomains          235795 non-null  int64
 5   has_ip_address                235795 non-null  int64
 6   uses_https                    235795 non-null  int64
 7   number_of_letters             235795 non-null  int64
 8   number_of_digits              235795 non-null  int64
 9   number_of_special_characters  235795 non-null  int64
 10  letter_ratio                  235795 non-null  float64
 11  digit_ratio                   235795 non-null  float64
 12  number_of_dots                235795 non-null  int64
 13  number_of_hyphens             235795 non-null  int64
 14  number_of_underscores         235795 non-null  int64
 15  number_of_slashes             235795 non-null  int64
 16  number_of_question_marks      235795 non-null  int64
 17  number_of_equal_signs         235795 non-null  int64
 18  number_of_ampersands          235795 non-null  int64
 19  number_of_at_symbols          235795 non-null  int64
 20  suspicious_keyword_count      235795 non-null  int64
 21  label                         235795 non-null  int64
dtypes: float64(2), int64(20)
memory usage: 39.6 MB

In [17]:
features_df.to_csv(
    "dataset_features.csv",
    index=False
)

In [18]:
features_df["label"].value_counts()

label
1    134850
0    100945
Name: count, dtype: int64